= Maven Installation

== Speedment Requirements
Before proceeding with the installation, please make sure that you have the following installed:

* Apache Maven version 3.5.0 or later
* Java version 8.0.40 or later (e.g. Java 11)

== Installation with Maven
Speedment is installed using [Apache Maven](https://maven.apache.org/) by including the Speedment dependencies in your pom.xml-file. You need to setup both the `speedment-maven-plugin` (for code generation) and the `speedment-runtime` (used by the application at runtime).

If starting a project from scratch, the Initializer can help you automatically generate a custom project pom-file. There are two different versions of the Initializer depending on which version of Speedment you intend to use:
* [Speedment Open Source Initializer](https://speedment.com/oss-download) is used to generate a pom-file for a Speedment OSS project.
* [Speedment Initializer](https://speedment.com/download) is used to generate a pom-file for any Speedment Stream/HyperStream project, including trials and free-licenses.

If you prefer to manually configure your pom.xml, see the [Maven guide](maven.html#top) for more detailed information about configuring the correct dependencies.

== Starting the Tool
Speedment uses JSON configuration files to generate Java code from your database. The JSON files will be created using the Speedment Tool. You can choose to start the Tool from your IDE* or run it from the command line.

=== With the Command Line
Locate the directory of your pom.xml-file and run the following:

`mvn speedment:tool`

=== With Your IDE
Launch the project as a Maven project in your IDE. A number of Maven goals associated with Speedment will be available. Use `speedment:tool` to connect to your database and generate a Java representation of the domain model.

NOTE: Speedment Maven Goals" caption="Speedment Maven Goals as shown in IntelliJ

NOTE: If you wish to use an existing JSON file, use `speedment:generate` instead.

The following process is divided in three steps:
1. Select a preferred license type (only applies to Enterprise projects)
1. Connect to the database
2. Configure the project and generate a Java Domain Model from the database

== Step 1. Select a license type (For Enterprise projects only)
When the tool launches for the first time you need to license your software. The graphical interface will leave you with three options:

* Use an existing license key for Stream or HyperStream
* Request a 30-day HyperStream trial
* Start a Free license which will provide access to all features of HyperStream for databases under 500 MB

== Step 2. Connect to the database
Next, simply fill out the database credentials and hit Connect.

NOTE: For security reasons, Speedment __never stores__ the database password in generated classes or configuration files.


== Step 3. Configure the project and generate code
Speedment now analyses the underlying data sources’ metadata and automatically creates code which directly reflects the structure (i.e. the “domain model”) of the data sources. Once finished, the database structure is visualized as a tree in the appearing window. To generate the object-oriented Java representation, press "Generate".

== Hello World
Once the files are generated, you are ready to write your first Java Stream query.

Here is a an application that will count the number of films that is rated "PG-13" from an example database named "Sakila".

[source, java]
----
     // Configure and start Speedment
     Speedment app = new SakilaApplicationBuilder()
        .withBundle(MySqlBundle.class)
        .withPassword("sakila-password")
        .build();

    // Get the FilmManager (that handles the 'film' table)
    FilmManager films = app.getOrThrow(FilmManager.class);

    // Here is the actual logic
    long count = films.stream()
        .filter(Film.RATING.equal("PG-13"))
        .count();

    // Print out the count
    System.out.format("There are %d films(s) with a PG-13 rating %n", count);
----

